apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  MONGODB_URI: "REPLACE_WITH_PROD_MONGODB_URI"
  CLERK_JWT_KEY: "REPLACE_WITH_PROD_CLERK_JWT_KEY"
  CORS_ORIGIN: "REPLACE_WITH_PROD_FRONTEND_URL"
