apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  NODE_ENV: "production"
  PORT: "3000"
  NEXT_PUBLIC_CLERK_PROXY_URL: "https://clerk.ai.tianlu.tech"
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "pk_live_Y2xlcmsuYWkudGlhbmx1LnRlY2gk"
  NEXT_PUBLIC_API_URL: "https://ai-api.tianlu.tech"
