apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tianluai-prod

namePrefix: prod-

resources:
  - ../../base

patches:
  - path: patches/namespace.yaml
  - path: patches/backend-deployment.yaml
  - path: patches/frontend-deployment.yaml
  - path: patches/backend-config.yaml
  - path: patches/frontend-config.yaml
  - path: patches/backend-secrets.yaml
  - path: patches/frontend-secrets.yaml
