apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  MONGODB_URI: "REPLACE_WITH_DEV_MONGODB_URI"
  CLERK_SECRET_KEY: "REPLACE_WITH_DEV_CLERK_SECRET_KEY"
  CORS_ORIGIN: "REPLACE_WITH_DEV_FRONTEND_URL"
