apiVersion: apps/v1
kind: Deployment
metadata:
  name: tianluai-web
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: web
          image: registry.digitalocean.com/tianluai/tianluai-web:latest
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
