apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  MONGODB_URI: "REPLACE_WITH_STAGING_MONGODB_URI"
  CLERK_SECRET_KEY: "REPLACE_WITH_STAGING_CLERK_SECRET_KEY"
  CORS_ORIGIN: "REPLACE_WITH_STAGING_FRONTEND_URL"
