apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  NODE_ENV: "staging"
  PORT: "3000"
  AUTH_URL: "https://ai-staging.tianlu.tech"
  NEXT_PUBLIC_API_URL: "https://ai-api-staging.tianlu.tech"
